name: CareerCraft
channels:
  - conda-forge
dependencies:
  - pip == 23.2.1
  - python == 3.9
  - spacy==3.7.1
  - pip:
      - python-docx == 1.0.1
      - Document == 1.0
      - openai == 0.28.0
      - PyMuPDF == 1.23.5
      - pypdf2 == 2.11.1
      - PyYAML == 6.0.1
      - docx == 0.2.4
      - lxml == 4.9.3
      - Pillow == 9.5.0
      - prefect
      - dotenv
