name: ETL Process

on:
  push:
    branches:
      - main

jobs:
  etl_process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Initialize Conda
        run: |
          conda init bash
          eval "$(conda shell.bash hook)"
          conda env create -f environment.yml
          conda activate CareerCraft

      - name: Install additional dependencies
        run: |
          pip install python-docx==1.0.1
          pip install pypdf2==2.11.1
          pip install Document==1.0
          pip install PyMuPDF==1.23.5
          pip install docx==0.2.4
          pip install spacy==3.6.1

      - name: Run ETL script
        run: |
          python etl/load.py

      - name: Check for changes
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Update data"
            git push
          else
            echo "No changes to commit"
          fi
